version: '3'
services:
  # frontend logic
  frontend:
    container_name: frontend
    image: ghcr.io/joaovitoriasilva/gearguardian/frontend:dev_29112023
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - /home/joaovitoriasilva/Documents/containers/gearguardian/frontend:/var/www/html
    ports:
      - "8080:80"
    restart: unless-stopped
    
  # API logic
  backend:
    container_name: backend
    image: ghcr.io/joaovitoriasilva/gearguardian/backend:dev_01122023
    environment:
      - DB_PASSWORD=changeme
      - SECRET_KEY=changeme
      - STRAVA_CLIENT_ID=changeme
      - STRAVA_CLIENT_SECRET=changeme
      - STRAVA_AUTH_CODE=changeme
    ports:
      - "98:80"
    volumes:
      - /home/joaovitoriasilva/Documents/containers/gearguardian/backend:/app
    env_file:
      - config/.env
    depends_on:
      - mariadb
      - jaeger
    restart: unless-stopped
  
  # mysql mariadb logic
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123Testes@
      - MYSQL_DATABASE=gearguardian
      - MYSQL_USER=gearguardian
      - MYSQL_PASSWORD=123Testes@
    ports:
      - "3306:3306"
    volumes:
      - /home/joaovitoriasilva/Documents/containers/mariadb:/var/lib/mysql
    restart: unless-stopped

  # Jaeger for opentelemetry
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    restart: unless-stopped

# phpmyadmin for DB manipulation
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
    restart: unless-stopped

networks:
  default:
    external: true
    name: backend_network