site_name: Endurain documentation
repo_url: https://github.com/joaovitoriasilva/endurain
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Integrations:
    - 3rd party apps:
      - RunnerUp: integrations/runnerup.md
      - Apple automations: integrations/apple-automations.md
    - 3rd party services:
      - Garmin Connect: integrations/garmin-connect.md
      - Strava: integrations/strava.md
  - About:
    - License: about/license.md