receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  jaeger:
    endpoint: "jaeger:14268"  # Use the service name defined in your Jaeger service

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]